name: B - Terraform Apply

on: workflow_dispatch

jobs:
  terraform:
    name: "Terraform apply"
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        shell: bash

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: us-east-1

    - name: Terraform init
      id: init
      run: |
        terraform init \
          -input=false -no-color \
          -backend-config="bucket=${{ secrets.BUCKET}}"

    - name: Terraform validation
      id: validate
      run: |
        terraform validate \
          -no-color

    - name: Terraform apply
      id: apply
      run: |
        terraform apply \
          -auto-approve -input=false -no-color \
          -var "pub_key_data=${{ secrets.WEBODM_PUB}}" 

    - name: Terraform output
      id: output
      run: |
        terraform output \
          -no-color
