name: X - Terraform Destroy

on: workflow_dispatch

jobs:
  terraform:
    name: "Terraform destroy"
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        role-session-name: terraform-destroy
        aws-region: us-east-2

    - name: Terraform init
      id: init
      run: |
        terraform init \
          -input=false -no-color \
          -backend-config="bucket=${{ secrets.BUCKET}}"

    - name: Terraform validation
      id: validate
      run: |
        terraform validate \
          -no-color

    - name: Terraform destroy
      id: apply
      run: |
        terraform apply \
          -destroy -auto-approve -input=false -no-color \
          -var "data_bucket=${{ secrets.DATA_BUCKET }}"
