name: Z - Terraform State Remove

on: workflow_dispatch

jobs:
  terraform:
    name: "Terraform state remove"
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        role-session-name: terraform-state-remove
        aws-region: us-east-1

    - name: S3 remove bucket file
      run: aws s3 rm s3://${{ secrets.BUCKET }}/terraform.tfstate